FLAGS = -Wall -pedantic

#too lazy to do a good one
all : 
	@rm -f ProcessusInit bus passager *.o *~ \#*
	@gcc -o ProcessusInit init.c $(FLAGS)
	@gcc -o bus bus.c $(FLAGS)
	@gcc -o passager passager.c $(FLAGS)



